Chirp observational init
OCHA-DAP/ds-aa-lac-dry-corridor pull request #2
Opened 2023-09-26 16:51 UTC by zackarno

light analysis of chirps monthly data

- CHIRPS daily data processed to monthly zonal stats [chirps_adm0_monthly](https://github.com/OCHA-DAP/ds-aa-lac-dry-corridor/blob/chirp-observational-init/data-raw/chirps_adm0_monthly.R). 
- 1 [Rmd notebook](https://github.com/OCHA-DAP/ds-aa-lac-dry-corridor/blob/chirp-observational-init/exploration/CHIRPS_Observational_Explore.Rmd) made to create 2 plots for initial request for information from CERF

You can just load the data directly in the notebook and checkout the graphs if you don't feel like setting up `{rgee}` and earth engine to do this PR review.

2023-09-27 08:49 UTC, caldwellst requested changes
Overall looks good! I would recommend looking at `styler` just to style your code easily with a single line of code, cause like in the Red there's lots of line breaks or missing spaces that can be automatically cleaned up (it doesn't create new breaks for functions on new lines, like it won't split `read_csv(file.path(` annoyingly, which you have to do yourself, but it will at least automate indentation and stuff.

I had a few other code comments in there which you'll see. On the Rmd, no specific comments on the code itself beyond the styling, but some questions and thoughts about the plots.

1. I don't think I would reverse the y axis, as it took me a LONG time to realise I wasn't looking at blue dots highlighting the wettest seasons. Maybe you had the issue of the lowest points being at different y axis values, not sure, but you could extend the y axis to 0 and keep that formatting and then clearly see where the low values lie.
2. I think it's hard to pull out the main findings we are interested in from all of the plots. I would try and create a couple of summary plots for the two seasons. You could do boxplots or violin charts for El Niño years vs. non El Niño years, in which case we could see how different the distributions are. You could do this overall and by country. As well, you could look at overall what % of driest years fall in El Niño years, to check if the extremes of the distribution differ.
3. I do not think you can consider January year 1 to December year 2 as the full El Niño. According to here for instance, http://www.bom.gov.au/climate/enso/history/ln-2010-12/ENSO-when.shtml#:~:text=A%20typical%20El%20Niño%20or,dissipate%20in%20the%20subsequent%20autumn., El Niño is typically from autumn to autumn in 2 years (southern hemisphere autumn), so maybe something like March 21 year 1 to June 21 year 2. Importantly, this means that your JJA season I think should only be in El Niño if it was in the first year.

2023-09-27 08:49 UTC, caldwellst commented on _targets.R
> +  packages = c("tibble") # packages that your targets need to run
What's the difference between the packages here and the library calls above?

2023-09-27 08:49 UTC, caldwellst commented on data-raw/chirps_adm0_monthly.R
> +                scale = 5566,
Why `scale = 5566`? Might be a useful comment here as the rationale/purpose isn't as clear as the rest of the arguments passed to the function.

2023-09-27 08:49 UTC, caldwellst commented on data-raw/chirps_adm0_monthly.R
> +                scale = 5566,
My intuition would be that this is simply giving us zonal statistics for adm0, so yeah, a bit confused by the `scale` argument.

2023-09-27 12:56 UTC, zackarno commented on data-raw/chirps_adm0_monthly.R
> +                scale = 5566,
- in GEE you have to supply scale which is just the scale of the raster when you export or extract anything. This is because it can auto-aggregate depending on zoom level - which can be desired, but usually not in these cases.
- 5566 is just the scale of CHIRPS (0.05) .
- Will add comment - good point

2023-09-29 14:25 UTC, zackarno commented
Thanks for the review - yes styler is sweet and I just forgot to run it.

I agree with all your points on the plots so will improve them and add a few more. 

- I'll adjust the axes or make it the plot more clear generally (maybe w/ raindrop points) 
-  adjust the El nino years as you recommended. 
- Regarding key takeaways - I'll make the plots you suggested since I think it's interesting and could be useful for our work messaging generally. However, i should have given you more background in my initial PR (or in the Rmd) - the analysis was not really done w/ the intention of comparing El Nino and non- El Nino rather just to give CERF and understanding of where we currently sit w/ respect to previous years (El Nino years just added for more reference points).

I'm going to leave this branch floating in branch world for a little while since it's actually not part of the trigger and just a one-off for current situational understanding. I'll let you know when I've integrated your suggestions.

2026-02-26 06:12 UTC, merged